#!/busybox static-sh

/busybox --install -s bin/
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t tmpfs none /tmp

# Add your own init tasks here:
#insmod mymodule.ko
#ifconfig eth0 10.0.0.2/24 up

exec /bin/sh -i
