#!/busybox static-sh

/busybox --install -s bin/
mount -t proc none /proc
mount -t sysfs none /sys
mount -t debugfs none /sys/kernel/debug
mount -t tmpfs none /tmp

# Add your own init tasks here:
#insmod mymodule.ko
#ifconfig eth0 10.0.0.2/24 up

echo "You are now in $(uname -r) under QEMU"
echo "Press C-a h for QEMU help"

# See https://github.com/brgl/busybox/blob/master/shell/cttyhack.c
# For more information about how cttyhack enabled job control on basic serial consoles
mknod -m 666 /dev/ttyS0 c 4 64
exec setsid cttyhack /bin/sh -i
